[package]
name = "kaspa-tx-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
# Wallet generation dependencies
bip39 = "2.0"
bip32 = "0.5"
blake2 = "0.10"
hex = "0.4"
# Basic dependencies
tokio = { version = "1.0", features = ["rt", "macros", "rt-multi-thread"] }
log = "0.4"
env_logger = "0.11"
